runtime: python311  # 사용하는 Python 버전
entrypoint: gunicorn -b :$PORT app:app  # 애플리케이션 시작점

automatic_scaling:  # 애플리케이션의 스케일링 설정
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic

instance_class: F1  # 애플리케이션 인스턴스의 사양

network:  # 네트워크 설정
  session_affinity: false